image: debian:latest

clone:
  depth: "full" # Prevents sonarcloud from showing a warning about shallow clone.

pipelines:
  default:
    - step:
        caches:
          - composer
        script:
          - apt update && apt install -y lsb-release apt-transport-https ca-certificates wget unzip curl
          - wget -O /etc/apt/trusted.gpg.d/php.gpg https://packages.sury.org/php/apt.gpg
          - echo "deb https://packages.sury.org/php/ $(lsb_release -sc) main" | tee /etc/apt/sources.list.d/php7.3.list
          - apt update && apt install -y php7.3 php7.3-http php7.3-xdebug php7.3-dom php7.3-mbstring
          - curl -sS https://getcomposer.org/installer | php -- --install-dir=/usr/local/bin --filename=composer
          - composer install
          - phpenmod xdebug
          - vendor/bin/phpunit
          - phpdismod xdebug
          - pipe: sonarsource/sonarcloud-scan:0.1.5
            variables:
              SONAR_TOKEN: ${SONAR_TOKEN} # Use a secure repository variable
              EXTRA_ARGS: -Dsonar.projectKey=ngvoice_asterisk-ari-client -Dsonar.organization=ngvoice -Dsonar.sources=./src -Dsonar.php.coverage.reportPaths=./tests/code-coverage-report.xml