image: php:latest

clone:
  depth: "full" # Prevents sonarcloud from showing a warning about shallow clone.

pipelines:
  default:
    - step:
        size: 2x # Adding more memory to the building docker container so it doesn't exceed memory
        caches:
          - composer
        script:
          - pecl install xdebug-2.9.0 && docker-php-ext-enable xdebug
              # Unzip and git are required by psr/log dependency
          - apt update && apt install -y unzip git
          - php -r "copy('https://getcomposer.org/installer', 'composer-setup.php');"
          - php -r "if (hash_file('sha384', 'composer-setup.php') === 'c5b9b6d368201a9db6f74e2611495f369991b72d9c8cbd3ffbc63edff210eb73d46ffbfce88669ad33695ef77dc76976') { echo 'Installer verified'; } else { echo 'Installer corrupt'; unlink('composer-setup.php'); } echo PHP_EOL;"
          - php composer-setup.php
          - php -r "unlink('composer-setup.php');"
          - ./composer.phar install
          - vendor/bin/phpunit --verbose -c phpunit.xml
          - pipe: sonarsource/sonarcloud-scan:0.1.5
            variables:
              SONAR_TOKEN: ${SONAR_TOKEN} # Using a secure repository variable
              EXTRA_ARGS: -Dsonar.projectKey=ngvoice_asterisk-ari-client -Dsonar.organization=ngvoice -Dsonar.sources=./src -Dsonar.php.coverage.reportPaths=./tests/code-coverage-report.xml